

// import {samplePage as eventsPage} from "./events-page";
import {samplePage as newsPage} from "./news-page";
// import {samplePage as cityGuidePage} from "./city-guide-page";

export const samplePage = newsPage;

export const sampleTempaltes = [
  {
    _id: {
      $oid: "6866958a06b04462eb97b673",
    },
    name: "TMP-Double Tween Text Inside",
    description: "A double tween block that has text inside",
    createdAt: {
      $date: "2025-07-03T14:36:16.925Z",
    },
    updatedAt: {
      $date: "2025-07-05T14:43:20.440Z",
    },
    tags: ["widget"],
    environmentId: {
      $oid: "686b51224327c0fddac32eae",
    },
    content: [
      {
        type: "SwiperSlider",
        props: {
          current: 2,
          slidesPerPage: 2,
          slidesObj: [
            {
              items: [
                {
                  type: "Flex",
                  props: {
                    items: [
                      {
                        type: "Text",
                        props: {
                          id: "Text-63580d4a-f92b-408b-8827-38c9ab6cb350",
                          align: "left",
                          text: {
                            content: "CHARMS",
                            chips: [],
                          },
                          size: "24px",
                          color: "default",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                      {
                        type: "Button",
                        props: {
                          id: "Button-bf5bd6bf-4ce6-465f-8101-2aee84ee0552",
                          label: {
                            content: "SHOP NOW",
                            chips: [],
                          },
                          href: {
                            content: "#",
                            chips: [],
                          },
                          align: "left",
                          variant: "link",
                          size: "default",
                          className: "",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                    ],
                    id: "Flex-45415223-01c8-4fc9-95bf-e2cb4be01001",
                    height: "40vh",
                    width: "100%",
                    justifyContent: "end",
                    direction: "column",
                    alignItems: "center",
                    gap: 15,
                    wrap: "wrap",
                    margin: "auto",
                    layout: {
                      spanCol: 1,
                      spanRow: 1,
                      padding: "0px",
                      margin: "0px",
                      grow: true,
                      alignSelf: "auto",
                      position: "static",
                      zIndex: 1,
                    },
                    backgroundColor: "transparent",
                    backgroundImageSrc: {
                      content: "/pages/homepage/immagine_carosello_1.1.jpg",
                    },
                    backgroundSize: "contain",
                    backgroundPosition: "center",
                    backgroundRepeat: "no-repeat",
                  },
                },
              ],
            },
            {
              items: [
                {
                  type: "Flex",
                  props: {
                    items: [
                      {
                        type: "Text",
                        props: {
                          id: "Text-39620db8-13e3-4c33-b1b2-6f03e11d7676",
                          align: "left",
                          text: {
                            content: "RINGS",
                            chips: [],
                          },
                          size: "24px",
                          color: "default",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                      {
                        type: "Button",
                        props: {
                          id: "Button-abc8dbe3-c2e6-4ced-96d1-bb22d10bab1c",
                          label: {
                            content: "SHOP NOW",
                            chips: [],
                          },
                          href: {
                            content: "#",
                            chips: [],
                          },
                          align: "left",
                          variant: "link",
                          size: "default",
                          className: "",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                    ],
                    id: "Flex-50525128-027d-4a86-b66e-1150e30e0cf7",
                    height: "40vh",
                    width: "100%",
                    justifyContent: "end",
                    direction: "column",
                    alignItems: "center",
                    gap: 15,
                    wrap: "wrap",
                    margin: "auto",
                    layout: {
                      spanCol: 1,
                      spanRow: 1,
                      padding: "0px",
                      margin: "0px",
                      grow: true,
                      alignSelf: "auto",
                      position: "static",
                      zIndex: 1,
                    },
                    backgroundColor: "transparent",
                    backgroundImageSrc: {
                      content: "/pages/homepage/immagine_carosello_1.2.jpg",
                    },
                    backgroundSize: "contain",
                    backgroundPosition: "center",
                    backgroundRepeat: "no-repeat",
                  },
                },
              ],
            },
            {
              items: [
                {
                  type: "Flex",
                  props: {
                    items: [
                      {
                        type: "Text",
                        props: {
                          id: "Text-c041bb1f-4af7-4818-8b1d-94ff31c3090d",
                          align: "left",
                          text: {
                            content: "CHARMS",
                            chips: [],
                          },
                          size: "24px",
                          color: "default",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                      {
                        type: "Button",
                        props: {
                          id: "Button-5fe428a6-d1e8-48d9-8c3c-1b3118d17809",
                          label: {
                            content: "SHOP NOW",
                            chips: [],
                          },
                          href: {
                            content: "#",
                            chips: [],
                          },
                          align: "left",
                          variant: "link",
                          size: "default",
                          className: "",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                    ],
                    id: "Flex-ef005abc-018b-4a0f-b4a4-373d2122f0c4",
                    height: "40vh",
                    width: "100%",
                    justifyContent: "end",
                    direction: "column",
                    alignItems: "center",
                    gap: 15,
                    wrap: "wrap",
                    margin: "auto",
                    layout: {
                      spanCol: 1,
                      spanRow: 1,
                      padding: "0px",
                      margin: "0px",
                      grow: true,
                      alignSelf: "auto",
                      position: "static",
                      zIndex: 1,
                    },
                    backgroundColor: "transparent",
                    backgroundImageSrc: {
                      content: "/pages/homepage/immagine_carosello_2.2.jpg",
                    },
                    backgroundSize: "contain",
                    backgroundPosition: "center",
                    backgroundRepeat: "no-repeat",
                  },
                },
              ],
            },
            {
              items: [
                {
                  type: "Flex",
                  props: {
                    items: [
                      {
                        type: "Text",
                        props: {
                          id: "Text-28f6d6c8-71fa-4211-ace8-20e7745980d9",
                          align: "left",
                          text: {
                            content: "CHARMS",
                            chips: [],
                          },
                          size: "24px",
                          color: "default",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                      {
                        type: "Button",
                        props: {
                          id: "Button-ce2311de-f5ec-4380-be33-be788a4938bd",
                          label: {
                            content: "SHOP NOW",
                            chips: [],
                          },
                          href: {
                            content: "#",
                            chips: [],
                          },
                          align: "left",
                          variant: "link",
                          size: "default",
                          className: "",
                          layout: {
                            spanCol: 1,
                            spanRow: 1,
                            padding: "0px",
                            margin: "0px",
                            grow: false,
                            alignSelf: "auto",
                            position: "static",
                            zIndex: 1,
                          },
                        },
                      },
                    ],
                    id: "Flex-fd82b4bc-1a89-4404-8ab8-8f6722b680e6",
                    height: "40vh",
                    width: "100%",
                    justifyContent: "end",
                    direction: "column",
                    alignItems: "center",
                    gap: 15,
                    wrap: "wrap",
                    margin: "auto",
                    layout: {
                      spanCol: 1,
                      spanRow: 1,
                      padding: "0px",
                      margin: "0px",
                      grow: true,
                      alignSelf: "auto",
                      position: "static",
                      zIndex: 1,
                    },
                    backgroundColor: "transparent",
                    backgroundImageSrc: {
                      content: "/pages/homepage/immagine_carosello_3.1.jpg",
                    },
                    backgroundSize: "contain",
                    backgroundPosition: "center",
                    backgroundRepeat: "no-repeat",
                  },
                },
              ],
            },
          ],
          spaceBetween: 50,
          loop: false,
          autoHeight: false,
          speed: 1000,
          autoplay: {
            enabled: false,
            delay: 1000,
            disableOnInteraction: false,
          },
          navigation: {
            enabled: false,
            placement: "outside",
          },
          pagination: {
            enabled: false,
            type: "normal",
          },
          breakpoints: [],
          layout: {
            spanCol: 2,
            spanRow: 1,
            padding: "0px",
            margin: "0px",
            grow: true,
            alignSelf: "auto",
            position: "static",
            zIndex: 1,
          },
          id: "SwiperSlider-e2065fc7-5b22-4b5b-b646-b31d7199e84d",
        },
      },
    ],
  },

  {
    _id: {
      $oid: "687144029368cdf723ee2729",
    },
    name: "TMP-Sostenibilità",
    description: "Template per la pagina sostenibilità",
    createdAt: {
      $date: "2025-07-11T17:03:23.422Z",
    },
    updatedAt: {
      $date: "2025-07-11T17:03:23.422Z",
    },
    tags: ["template"],
    content: [
      {
        type: "FlexVideo",
        props: {
          items: [
            {
              type: "Grid",
              props: {
                items: [
                  {
                    type: "Flex",
                    props: {
                      items: [
                        {
                          type: "Text",
                          props: {
                            id: "Text-09022faa-28da-4f2b-a97b-8046ac569855",
                            align: "left",
                            text: {
                              content: "SOSTENIBILITÀ",
                              chips: [],
                            },
                            size: "41px",
                            color: "#ffffff",
                            fontWeight: "400",
                            fontStyle: "normal",
                            maxWidth: "100%",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              marginTop: "0px",
                              marginBottom: "0px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: false,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                            fontFamily: "Didot LT Std",
                          },
                        },
                        {
                          type: "Flex",
                          props: {
                            items: [
                              {
                                type: "Text",
                                props: {
                                  id: "Text-eb9915f5-ea0a-414c-b26a-d88b98d36556",
                                  align: "left",
                                  text: {
                                    content:
                                      "Leadership in action: DoDo è una community che agisce concretamente per sostenibilità, equità e inclusione. Protagonisti del cambiamento attraverso progetti culturali e iniziative di impatto sociale. Le nostre partnership parlano chiaro: dal Kering Responsible Gold Framework alla collaborazione quasi ventennale con WWF Italia, definiamo gli standard del settore.",
                                    chips: [],
                                  },
                                  size: "12px",
                                  color: "#f7f7f7",
                                  fontWeight: "500",
                                  fontStyle: "normal",
                                  maxWidth: "80%",
                                  layout: {
                                    spanCol: 1,
                                    spanRow: 1,
                                    paddingTop: "0px",
                                    paddingBottom: "0px",
                                    paddingLeft: "0px",
                                    paddingRight: "32px",
                                    marginTop: "0px",
                                    marginBottom: "0px",
                                    marginLeft: "0px",
                                    marginRight: "0px",
                                    grow: false,
                                    alignSelf: "auto",
                                    position: "static",
                                    zIndex: 1,
                                    width: "100%",
                                  },
                                  fontFamily: "Gotham",
                                  lineHeight: "28px",
                                },
                              },
                            ],
                            id: "Flex-16fa13cd-4bae-4b7e-b7b2-7786e3e97eff",
                            height: "100%",
                            width: "100%",
                            justifyContent: "start",
                            direction: "column",
                            alignItems: "start",
                            gap: 24,
                            wrap: "nowrap",
                            margin: "0",
                            border: "none",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              width: "unset",
                              marginTop: "0px",
                              marginBottom: "0px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: true,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                            backgroundOverlay: "",
                            backgroundColor: "transparent",
                            backgroundImageSrc: {
                              content: "",
                            },
                            backgroundSize: "contain",
                            backgroundPosition: "center",
                            backgroundRepeat: "no-repeat",
                            className: "",
                          },
                        },
                      ],
                      id: "Flex-0c4d6039-64ea-4d97-b929-e9947f6e98f8",
                      height: "100%",
                      width: "90%",
                      justifyContent: "start",
                      direction: "column",
                      alignItems: "start",
                      gap: 2,
                      wrap: "wrap",
                      margin: "auto",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "0px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: true,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                      },
                      backgroundColor: "transparent",
                      backgroundImageSrc: {
                        content: "",
                      },
                      backgroundSize: "contain",
                      backgroundPosition: "left",
                      backgroundRepeat: "no-repeat",
                    },
                  },
                ],
                id: "Grid-821c0584-848d-4331-af30-3280a7f8d671",
                numColumns: 2,
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "80px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "0px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: false,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                  width: "",
                  mobile: {
                    paddingLeft: "0px",
                  },
                },
                gap: "0px",
                mobile: {},
              },
            },
          ],
          height: "80vh",
          width: "100%",
          justifyContent: "center",
          direction: "row",
          alignItems: "center",
          gap: 24,
          wrap: "wrap",
          margin: "auto",
          useOverlay: false,
          layout: {
            spanCol: 1,
            spanRow: 1,
            paddingTop: "0px",
            paddingBottom: "0px",
            paddingLeft: "0px",
            paddingRight: "0px",
            marginTop: "0px",
            marginBottom: "0px",
            marginLeft: "0px",
            marginRight: "0px",
            grow: true,
            alignSelf: "auto",
            position: "static",
            zIndex: 1,
          },
          backgroundColor: "transparent",
          backgroundImage: "",
          backgroundSize: "contain",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          videoShowControls: false,
          videoAutoplay: true,
          videoLoop: true,
          videoMuted: true,
          id: "FlexVideo-1d3340d7-50b9-4a98-b0da-9d74d40a0236",
          videoSrc: {
            content: "/pages/sustainability/VideoLive/sustDesktop.mp4",
            chips: [],
          },
          videoMobileSrc: {
            content: "/pages/sustainability/VideoLive/sustMobile.mp4",
            chips: [],
          },
        },
      },
      {
        type: "Space",
        props: {
          direction: "",
          size: "24px",
          id: "Space-e70998c3-d739-4555-9db9-78ef1155cde6",
        },
      },
      {
        type: "Space",
        props: {
          direction: "",
          size: "24px",
          id: "Space-4299b77a-2255-4a16-9cd6-a658b19aff2f",
        },
      },
      {
        type: "Grid",
        props: {
          items: [
            {
              type: "Flex",
              props: {
                items: [
                  {
                    type: "Flex",
                    props: {
                      items: [
                        {
                          type: "Text",
                          props: {
                            id: "Text-de342f40-33c9-4818-aa52-988aca5d3800",
                            align: "left",
                            text: {
                              content: "DODO:",
                              chips: [],
                            },
                            size: "32px",
                            color: "#ffffff",
                            fontWeight: "400",
                            fontStyle: "normal",
                            maxWidth: "100%",
                            className: "",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              width: "unset",
                              marginTop: "0px",
                              marginBottom: "0px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: false,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                            fontFamily: "Didot LT Std",
                          },
                        },
                        {
                          type: "Text",
                          props: {
                            id: "Text-370f8d44-050e-4c9a-98f4-ae64641c2fd0",
                            align: "center",
                            text: {
                              content: "NOME, MISSIONE, NATURA\n\n",
                              chips: [],
                            },
                            size: "32px",
                            color: "#ffffff",
                            fontWeight: "400",
                            fontStyle: "normal",
                            maxWidth: "100%",
                            className: "",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              width: "unset",
                              marginTop: "0px",
                              marginBottom: "0px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: false,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                            fontFamily: "Didot LT Std",
                          },
                        },
                        {
                          type: "Button",
                          props: {
                            id: "Button-0b893e25-cc53-408f-b133-3519ce5a2ef2",
                            label: "",
                            href: "",
                            align: "left",
                            variant: "link",
                            size: "default",
                            backgroundColor: "",
                            textColor: "#ffffff",
                            className: "",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              width: "unset",
                              marginTop: "32px",
                              marginBottom: "32px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: false,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                          },
                        },
                      ],
                      id: "Flex-16a6d59f-bf80-4c1f-8f01-69af6c106846",
                      height: "100%",
                      width: "100%",
                      justifyContent: "end",
                      direction: "column",
                      alignItems: "center",
                      gap: 0,
                      wrap: "wrap",
                      margin: "auto",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "0px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        width: "unset",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: true,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                        mobile: {
                          paddingRight: "20px",
                          paddingLeft: "20px",
                          marginLeft: "20px",
                          marginRight: "20px",
                        },
                      },
                      backgroundOverlay: "",
                      backgroundColor: "transparent",
                      backgroundImageSrc: {
                        content: "",
                      },
                      backgroundSize: "contain",
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      className: "",
                    },
                  },
                ],
                id: "Flex-e6eec8d8-53dd-40d1-ab46-43594f363974",
                height: "75vh",
                width: "100%",
                justifyContent: "end",
                direction: "column",
                alignItems: "center",
                gap: 0,
                wrap: "wrap",
                margin: "auto",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "24px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                  width: "100%",
                },
                backgroundColor: "transparent",
                backgroundImageSrc: {
                  content:
                    "/pages/sustainability/banner-pagina-sustainability-dodo-600x600px-01.jpg",
                },
                backgroundSize: "cover",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                backgroundOverlay:
                  "linear-gradient(180deg, rgba(0, 0, 0, 0.00) 0%, rgba(0, 0, 0, 0.73) 66%)",
              },
            },
            {
              type: "Flex",
              props: {
                items: [
                  {
                    type: "Flex",
                    props: {
                      items: [
                        {
                          type: "Flex",
                          props: {
                            items: [
                              {
                                type: "Text",
                                props: {
                                  id: "Text-b957ca53-40b7-45cd-86fc-7dec2ac108ed",
                                  align: "center",
                                  text: {
                                    content:
                                      "\nLA STRATEGIA SOSTENIBILE DI DODO: CONSCIOUSNESS, MINDSET, COMMUNITY",
                                    chips: [],
                                  },
                                  size: "32px",
                                  color: "#ffffff",
                                  fontWeight: "300",
                                  fontStyle: "normal",
                                  maxWidth: "100%",
                                  className: "",
                                  layout: {
                                    spanCol: 1,
                                    spanRow: 1,
                                    paddingTop: "0px",
                                    paddingBottom: "0px",
                                    paddingLeft: "0px",
                                    paddingRight: "0px",
                                    width: "unset",
                                    marginTop: "0px",
                                    marginBottom: "0px",
                                    marginLeft: "0px",
                                    marginRight: "0px",
                                    grow: false,
                                    alignSelf: "auto",
                                    position: "static",
                                    zIndex: 1,
                                  },
                                  fontFamily: "Didot LT Std",
                                },
                              },
                            ],
                            id: "Flex-fcd9423b-1d0b-4933-96d8-a8de35b681eb",
                            height: "100%",
                            width: "80%",
                            justifyContent: "end",
                            direction: "row",
                            alignItems: "end",
                            gap: 24,
                            wrap: "wrap",
                            margin: "auto",
                            border: "none",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              width: "unset",
                              marginTop: "0px",
                              marginBottom: "0px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: true,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                            backgroundOverlay: "",
                            backgroundColor: "transparent",
                            backgroundImageSrc: {
                              content: "",
                            },
                            backgroundSize: "contain",
                            backgroundPosition: "center",
                            backgroundRepeat: "no-repeat",
                            className: "",
                          },
                        },
                        {
                          type: "Button",
                          props: {
                            id: "Button-e310e007-3fd4-4f0c-bf93-d3cec41a98fd",
                            label: "",
                            href: "",
                            align: "left",
                            variant: "link",
                            size: "default",
                            backgroundColor: "",
                            textColor: "#ffffff",
                            className: "",
                            layout: {
                              spanCol: 1,
                              spanRow: 1,
                              paddingTop: "0px",
                              paddingBottom: "0px",
                              paddingLeft: "0px",
                              paddingRight: "0px",
                              width: "unset",
                              marginTop: "32px",
                              marginBottom: "32px",
                              marginLeft: "0px",
                              marginRight: "0px",
                              grow: false,
                              alignSelf: "auto",
                              position: "static",
                              zIndex: 1,
                            },
                          },
                        },
                      ],
                      id: "Flex-554908d0-2cf8-44d7-8f8b-68d8de2e0576",
                      height: "80vh",
                      width: "100%",
                      justifyContent: "end",
                      direction: "column",
                      alignItems: "center",
                      gap: 0,
                      wrap: "wrap",
                      margin: "auto",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "0px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        width: "100%",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: true,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                        mobile: {
                          paddingTop: "",
                          paddingRight: "20px",
                          paddingLeft: "20px",
                          marginRight: "20px",
                          marginBottom: "20px",
                        },
                      },
                      backgroundOverlay: "",
                      backgroundColor: "transparent",
                      backgroundImageSrc: {
                        content: "",
                      },
                      backgroundSize: "contain",
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      className: "",
                    },
                  },
                ],
                id: "Flex-01ab61bf-c32f-4b77-9ecd-fb933fba9099",
                height: "75vh",
                width: "100%",
                justifyContent: "end",
                direction: "column",
                alignItems: "center",
                gap: 0,
                wrap: "wrap",
                margin: "auto",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "24px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                },
                backgroundColor: "transparent",
                backgroundImageSrc: {
                  content:
                    "/pages/sustainability/banner-pagina-sustainability-dodo-600x600px-012.jpg",
                },
                backgroundSize: "cover",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                backgroundOverlay:
                  "linear-gradient(180deg, rgba(0, 0, 0, 0.00) 0%, rgba(0, 0, 0, 0.73) 66%)",
              },
            },
          ],
          numColumns: 2,
          layout: {
            spanCol: 1,
            spanRow: 1,
            paddingTop: "0px",
            paddingBottom: "0px",
            paddingLeft: "0px",
            paddingRight: "0px",
            marginTop: "90px",
            marginBottom: "100px",
            marginLeft: "auto",
            marginRight: "auto",
            grow: false,
            alignSelf: "auto",
            position: "static",
            zIndex: 1,
            width: "80%",
          },
          id: "Grid-dd1224e0-55c6-4679-b98e-c9e128d0a411",
          gap: "10px",
          mobile: {},
        },
      },
      {
        type: "Space",
        props: {
          direction: "",
          size: "24px",
          id: "Space-20029b8e-bc1f-4df7-bb7b-f6d1b98d065c",
        },
      },
      {
        type: "Space",
        props: {
          direction: "",
          size: "24px",
          id: "Space-051553df-430c-488a-b6dc-38f1ecff62ea",
        },
      },
      {
        type: "Flex",
        props: {
          items: [
            {
              type: "Text",
              props: {
                align: "center",
                text: {
                  content: "PROUD TO BE DODO",
                  chips: [],
                },
                size: "32px",
                color: "#000000",
                fontWeight: "700",
                fontStyle: "normal",
                maxWidth: "100%",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "22px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "center",
                  position: "static",
                  zIndex: 1,
                  mobile: {
                    alignSelf: "center",
                    paddingLeft: "10px",
                    paddingRight: "10px",
                    marginRight: "30px",
                    marginBottom: "",
                    marginLeft: "30px",
                  },
                },
                id: "Text-46a7dab2-190f-4735-8444-142824273d5b",
                fontFamily: "Didot LT Std",
              },
            },
          ],
          height: "100%",
          width: "100%",
          justifyContent: "start",
          direction: "row",
          alignItems: "start",
          gap: 24,
          wrap: "wrap",
          margin: "auto",
          layout: {
            spanCol: 1,
            spanRow: 1,
            paddingTop: "0px",
            paddingBottom: "0px",
            paddingLeft: "0px",
            paddingRight: "0px",
            marginTop: "0px",
            marginBottom: "0px",
            marginLeft: "0px",
            marginRight: "0px",
            grow: true,
            alignSelf: "auto",
            position: "static",
            zIndex: 1,
          },
          backgroundColor: "transparent",
          backgroundImageSrc: {
            content: "",
          },
          backgroundSize: "contain",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          id: "Flex-29e7b231-2de8-440d-8efa-fe0173c4af3a",
        },
      },
      {
        type: "Grid",
        props: {
          items: [
            {
              type: "Flex",
              props: {
                items: [
                  {
                    type: "Image",
                    props: {
                      id: "Image-87596f39-0926-4529-b081-4fd63e397dd4",
                      src: {
                        content:
                          "/pages/sustainability/banner-pagina-sustainability-dodo-900x900px-014.jpg",
                      },
                      alt: {
                        content: "Image description",
                      },
                      width: "auto",
                      height: "auto",
                      alignment: "center",
                      caption: "",
                      showCaption: false,
                      hasBorder: false,
                      borderWidth: "1px",
                      borderColor: "#000000",
                      borderRadius: "0px",
                      shadow: "none",
                      linkUrl: "",
                      openInNewTab: true,
                      objectFit: "cover",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "45px",
                        paddingBottom: "45px",
                        paddingLeft: "45px",
                        paddingRight: "45px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                        mobile: {
                          paddingTop: "20px",
                          paddingBottom: "20px",
                          paddingRight: "20px",
                          paddingLeft: "20px",
                        },
                      },
                    },
                  },
                  {
                    type: "Text",
                    props: {
                      id: "Text-a301c44c-5cc5-4b10-b0cb-4d81340c146e",
                      align: "left",
                      text: {
                        content: "WWF Italia",
                        chips: [],
                      },
                      size: "24px",
                      color: "#000000",
                      fontWeight: "300",
                      fontStyle: "normal",
                      maxWidth: "100%",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "40px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                      },
                      fontFamily: "Didot LT Std",
                    },
                  },
                  {
                    type: "Space",
                    props: {
                      id: "Space-aa1faf64-dcb8-4718-ae71-d1e66176ba7c",
                      direction: "",
                      size: "24px",
                    },
                  },
                ],
                id: "Flex-c2b6625f-6517-43b3-9be4-48fe11e1c5e0",
                height: "100%",
                width: "100%",
                justifyContent: "center",
                direction: "column",
                alignItems: "center",
                gap: 24,
                wrap: "wrap",
                margin: "auto",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "0px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                },
                backgroundColor: "transparent",
                backgroundImageSrc: {
                  content: "",
                },
                backgroundSize: "contain",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                className: "sustainability-grid-item",
              },
            },
            {
              type: "Flex",
              props: {
                items: [
                  {
                    type: "Image",
                    props: {
                      id: "Image-7cd7cdcc-580e-4b15-a42f-1eaa966ed268",
                      src: {
                        content:
                          "/pages/sustainability/banner-pagina-sustainability-dodo-900x900px-012.jpg",
                      },
                      alt: {
                        content: "Image description",
                      },
                      width: "auto",
                      height: "auto",
                      alignment: "center",
                      caption: "",
                      showCaption: false,
                      hasBorder: false,
                      borderWidth: "1px",
                      borderColor: "#000000",
                      borderRadius: "0px",
                      shadow: "none",
                      linkUrl: "",
                      openInNewTab: true,
                      objectFit: "cover",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "45px",
                        paddingBottom: "45px",
                        paddingLeft: "45px",
                        paddingRight: "45px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                        mobile: {
                          paddingRight: "20px",
                          paddingBottom: "20px",
                          paddingTop: "20px",
                          paddingLeft: "20px",
                        },
                      },
                      className: "",
                    },
                  },
                  {
                    type: "Text",
                    props: {
                      id: "Text-6d79d51b-3ee7-4b00-b74b-4324908d6a5e",
                      align: "left",
                      text: {
                        content: "Tenaka",
                        chips: [],
                      },
                      size: "24px",
                      color: "#000000",
                      fontWeight: "300",
                      fontStyle: "normal",
                      maxWidth: "100%",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "45px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                      },
                      fontFamily: "Didot LT Std",
                    },
                  },
                  {
                    type: "Space",
                    props: {
                      id: "Space-3c32c518-b2b0-49ab-ad6a-1da3b8af85e3",
                      direction: "",
                      size: "24px",
                    },
                  },
                ],
                id: "Flex-11c2e328-afd6-4f2c-9ef9-8de1d3eeed4a",
                height: "100%",
                width: "100%",
                justifyContent: "center",
                direction: "column",
                alignItems: "center",
                gap: 24,
                wrap: "wrap",
                margin: "auto",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "0px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                },
                backgroundColor: "transparent",
                backgroundImageSrc: {
                  content: "",
                },
                backgroundSize: "contain",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                className: "sustainability-grid-item",
              },
            },
            {
              type: "Flex",
              props: {
                items: [
                  {
                    type: "Image",
                    props: {
                      id: "Image-f67837c8-10dc-466e-9473-e9afd7e602eb",
                      src: {
                        content:
                          "/pages/sustainability/banner-pagina-sustainability-dodo-900x900px-01.jpg",
                      },
                      alt: {
                        content: "Image description",
                      },
                      width: "auto",
                      height: "auto",
                      alignment: "center",
                      caption: "",
                      showCaption: false,
                      hasBorder: false,
                      borderWidth: "1px",
                      borderColor: "#000000",
                      borderRadius: "0px",
                      shadow: "none",
                      linkUrl: "",
                      openInNewTab: true,
                      objectFit: "cover",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "45px",
                        paddingBottom: "45px",
                        paddingLeft: "45px",
                        paddingRight: "45px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                        mobile: {
                          paddingTop: "20px",
                          paddingBottom: "20px",
                          paddingRight: "20px",
                          paddingLeft: "20px",
                        },
                      },
                    },
                  },
                  {
                    type: "Text",
                    props: {
                      id: "Text-2cbf6270-98c5-46e9-82e3-71b024fbedd0",
                      align: "left",
                      text: {
                        content: "Casa Arcobaleno",
                        chips: [],
                      },
                      size: "24px",
                      color: "#000000",
                      fontWeight: "300",
                      fontStyle: "normal",
                      maxWidth: "100%",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "45px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                      },
                      fontFamily: "Didot LT Std",
                    },
                  },
                  {
                    type: "Space",
                    props: {
                      id: "Space-775c528a-42aa-4aab-aa15-21f0a4bd5ded",
                      direction: "",
                      size: "24px",
                    },
                  },
                ],
                id: "Flex-3afbfc0d-3c3b-4edc-ad6d-05c328414d4d",
                height: "100%",
                width: "100%",
                justifyContent: "center",
                direction: "column",
                alignItems: "center",
                gap: 24,
                wrap: "wrap",
                margin: "auto",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "0px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                },
                backgroundColor: "transparent",
                backgroundImageSrc: {
                  content: "",
                },
                backgroundSize: "contain",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                className: "sustainability-grid-item",
              },
            },
            {
              type: "Flex",
              props: {
                items: [
                  {
                    type: "Image",
                    props: {
                      id: "Image-1fbc3f5a-787d-4d04-8173-69e8cc79be52",
                      src: {
                        content:
                          "/pages/sustainability/banner-pagina-sustainability-dodo-900x900px-013.jpg",
                      },
                      alt: {
                        content: "Image description",
                      },
                      width: "auto",
                      height: "auto",
                      alignment: "center",
                      caption: "",
                      showCaption: false,
                      hasBorder: false,
                      borderWidth: "1px",
                      borderColor: "#000000",
                      borderRadius: "0px",
                      shadow: "none",
                      linkUrl: "",
                      openInNewTab: true,
                      objectFit: "cover",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "45px",
                        paddingBottom: "45px",
                        paddingLeft: "45px",
                        paddingRight: "45px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                        mobile: {
                          paddingBottom: "20px",
                          paddingTop: "20px",
                          paddingRight: "20px",
                          paddingLeft: "20px",
                        },
                      },
                    },
                  },
                  {
                    type: "Text",
                    props: {
                      id: "Text-d482ce50-ef02-4477-ac40-68cfbf9ba1fb",
                      align: "left",
                      text: {
                        content: "Treedom",
                        chips: [],
                      },
                      size: "24px",
                      color: "#000000",
                      fontWeight: "300",
                      fontStyle: "normal",
                      maxWidth: "100%",
                      layout: {
                        spanCol: 1,
                        spanRow: 1,
                        paddingTop: "0px",
                        paddingBottom: "45px",
                        paddingLeft: "0px",
                        paddingRight: "0px",
                        marginTop: "0px",
                        marginBottom: "0px",
                        marginLeft: "0px",
                        marginRight: "0px",
                        grow: false,
                        alignSelf: "auto",
                        position: "static",
                        zIndex: 1,
                      },
                      fontFamily: "Didot LT Std",
                    },
                  },
                  {
                    type: "Space",
                    props: {
                      id: "Space-be7b6779-e39a-471f-8fe5-a4f0d31cb153",
                      direction: "",
                      size: "24px",
                    },
                  },
                ],
                id: "Flex-78e69c2c-2378-4a08-abbb-c5655a5724d3",
                height: "100%",
                width: "100%",
                justifyContent: "center",
                direction: "column",
                alignItems: "center",
                gap: 24,
                wrap: "wrap",
                margin: "auto",
                layout: {
                  spanCol: 1,
                  spanRow: 1,
                  paddingTop: "0px",
                  paddingBottom: "0px",
                  paddingLeft: "0px",
                  paddingRight: "0px",
                  marginTop: "0px",
                  marginBottom: "0px",
                  marginLeft: "0px",
                  marginRight: "0px",
                  grow: true,
                  alignSelf: "auto",
                  position: "static",
                  zIndex: 1,
                },
                backgroundColor: "transparent",
                backgroundImageSrc: {
                  content: "",
                },
                backgroundSize: "contain",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
                className: "sustainability-grid-item",
              },
            },
          ],
          numColumns: 4,
          layout: {
            spanCol: 1,
            spanRow: 1,
            paddingTop: "0px",
            paddingBottom: "0px",
            paddingLeft: "30px",
            paddingRight: "30px",
            marginTop: "0px",
            marginBottom: "140px",
            marginLeft: "0px",
            marginRight: "0px",
            grow: false,
            alignSelf: "auto",
            position: "static",
            zIndex: 1,
            mobile: {
              marginRight: "30px",
              marginLeft: "30px",
            },
          },
          id: "Grid-0a2a3e7f-8db3-469c-832e-221b4a08acd0",
          gap: "10px",
          mobile: {},
        },
      },
      {
        type: "Space",
        props: {
          direction: "",
          size: "24px",
          id: "Space-6f89616a-f737-42e7-96b9-c3d1db507ba6",
        },
      },
    ],
    environmentId: {
      $oid: "686b51224327c0fddac32eae",
    },
  },
];
