export const samplePage = {
  _id: {
    $oid: "68ed04150f7ef9e4a36d33ce",
  },
  status: "PUBLISHED",
  _created_at: {
    $date: "2024-04-03T08:52:04.944Z",
  },
  _updated_at: {
    $date: "2025-11-17T08:12:48.576Z",
  },
  createdById: {
    $oid: "67daa7b65b96afe71bfb79b3",
  },
  content: [
    {
      type: "Grid",
      props: {
        items: [
          {
            type: "Text",
            props: {
              id: "Text-e43af001-7b97-4d59-a503-6f4bf9bd6bfe",
              useEvent: false,
              align: "left",
              text: {
                content: "Text",
              },
              size: "16px",
              color: "#000000",
              fontWeight: "400",
              fontStyle: "normal",
              maxWidth: "100%",
              className: "",
              mobile: {},
              layout: {
                spanCol: 1,
                spanRow: 1,
                paddingTop: "0px",
                paddingBottom: "0px",
                paddingLeft: "0px",
                paddingRight: "0px",
                width: "auto",
                marginTop: "0px",
                marginBottom: "0px",
                marginLeft: "0px",
                marginRight: "0px",
                grow: false,
                alignSelf: "auto",
                position: "static",
                zIndex: 1,
                order: 0,
                mobile: {},
              },
            },
          },
          {
            type: "Text",
            props: {
              id: "Text-e5b19cbf-e726-47dc-9055-7914ec3092e1",
              useEvent: false,
              align: "left",
              text: {
                content: "Text",
              },
              size: "16px",
              color: "#000000",
              fontWeight: "400",
              fontStyle: "normal",
              maxWidth: "100%",
              className: "",
              mobile: {},
              layout: {
                spanCol: 1,
                spanRow: 1,
                paddingTop: "0px",
                paddingBottom: "0px",
                paddingLeft: "0px",
                paddingRight: "0px",
                width: "auto",
                marginTop: "0px",
                marginBottom: "0px",
                marginLeft: "0px",
                marginRight: "0px",
                grow: false,
                alignSelf: "auto",
                position: "static",
                zIndex: 1,
                order: 0,
                mobile: {},
              },
            },
          },
          {
            type: "Text",
            props: {
              id: "Text-9d5ffbc3-221b-4943-bd4d-95c36511004e",
              useEvent: false,
              align: "left",
              text: {
                content: "Text",
              },
              size: "16px",
              color: "#000000",
              fontWeight: "400",
              fontStyle: "normal",
              maxWidth: "100%",
              className: "",
              mobile: {},
              layout: {
                spanCol: 1,
                spanRow: 1,
                paddingTop: "0px",
                paddingBottom: "0px",
                paddingLeft: "0px",
                paddingRight: "0px",
                width: "auto",
                marginTop: "0px",
                marginBottom: "0px",
                marginLeft: "0px",
                marginRight: "0px",
                grow: false,
                alignSelf: "auto",
                position: "static",
                zIndex: 1,
                order: 0,
                mobile: {},
              },
            },
          },
          {
            type: "Text",
            props: {
              id: "Text-7e88c617-2ee6-4aeb-b797-d2db43f2a90c",
              useEvent: false,
              align: "left",
              text: {
                content: "Text",
              },
              size: "16px",
              color: "#000000",
              fontWeight: "400",
              fontStyle: "normal",
              maxWidth: "100%",
              className: "",
              mobile: {},
              layout: {
                spanCol: 1,
                spanRow: 1,
                paddingTop: "0px",
                paddingBottom: "0px",
                paddingLeft: "0px",
                paddingRight: "0px",
                width: "auto",
                marginTop: "0px",
                marginBottom: "0px",
                marginLeft: "0px",
                marginRight: "0px",
                grow: false,
                alignSelf: "auto",
                position: "static",
                zIndex: 1,
                order: 0,
                mobile: {},
              },
            },
          },
        ],
        useEvent: false,
        numColumns: 4,
        gap: "24px",
        numColumnsOptions: [],
        hideOnDesktop: false,
        hideOnMobile: false,
        hideOnTablet: false,
        mobile: {
          numColumns: 2,
          gap: "0px",
        },
        tablet: {
          numColumns: 2,
          gap: "0px",
        },
        layout: {
          spanCol: 1,
          spanRow: 1,
          paddingTop: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          width: "auto",
          marginTop: "0px",
          marginBottom: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          grow: false,
          alignSelf: "auto",
          position: "static",
          zIndex: 1,
          order: 0,
          mobile: {},
        },
        id: "Grid-0c2aa4f7-7305-400d-bdaf-3fb128ba62fc",
      },
    },
  ],
  draftContent: null,
};